Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/ElseAlignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
